# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RFMainDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RFMainDemo

    pod 'Masonry'
    pod 'MJRefresh'

end
